# Generated by Django 4.2.23 on 2026-09-01 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoRegistrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('token', models.CharField(max_length=255, verbose_name='Token del dispositivo')),
                ('plataforma', models.IntegerField(choices=[(1, 'Android'), (2, 'iOS')], default=1, verbose_name='Plataforma')),
                ('app_version', models.CharField(blank=True, default='', max_length=20, verbose_name='Versión de la app')),
                ('modelo_dispositivo', models.CharField(blank=True, default='', max_length=120, verbose_name='Modelo del dispositivo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo registrado',
                'verbose_name_plural': 'Dispositivos registrados',
                'ordering': ['-fecha_modificacion'],
                'unique_together': {('usuario', 'token')},
            },
        ),
    ]
