# Generated by Django 4.2.23 on 2026-09-02 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionAppMovil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('plataforma', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10, unique=True, verbose_name='Plataforma')),
                ('version_minima', models.CharField(default='1.0.0', max_length=20, verbose_name='Versión mínima soportada')),
                ('version_actual', models.CharField(default='1.0.0', max_length=20, verbose_name='Versión actual')),
                ('forzar_actualizacion', models.BooleanField(default=False, verbose_name='Forzar actualización global')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versión App Móvil',
                'verbose_name_plural': 'Versiones App Móvil',
            },
        ),
    ]
