# Generated by Django 4.2.23 on 2026-09-02 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_versionappmovil'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaNotificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Notificaciones push habilitadas')),
                ('grades', models.BooleanField(default=True, verbose_name='Avisos de calificaciones y notas')),
                ('attendance', models.BooleanField(default=True, verbose_name='Avisos de asistencia y faltas')),
                ('events', models.BooleanField(default=True, verbose_name='Avisos de calendario y eventos')),
                ('announcements', models.BooleanField(default=True, verbose_name='Avisos y comunicados generales')),
                ('tasks', models.BooleanField(default=True, verbose_name='Avisos de tareas y planificación')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de notificación',
                'verbose_name_plural': 'Preferencias de notificación',
            },
        ),
    ]
