# Generated by Django 4.2.23 on 2026-09-02 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_preferencianotificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMovil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('tipo', models.CharField(choices=[('SUGERENCIA', 'Sugerencia'), ('QUEJA', 'Queja'), ('ERROR', 'Error')], default='SUGERENCIA', max_length=20, verbose_name='Tipo de feedback')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback móvil',
                'verbose_name_plural': 'Feedbacks móviles',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
